version: '3.8'
services:
  backend:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
      - timescaledb
    volumes:
      - .:/app

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescale_db
    environment:
      POSTGRES_DB: ${TIMESCALE_DB}
      POSTGRES_USER: ${TIMESCALE_USER}
      POSTGRES_PASSWORD: ${TIMESCALE_PASSWORD}
    ports:
      - "5434:5432"

volumes:
  pgdata:
