[tool.black]
line-length = 80
target-version = ['py311']
exclude = '''
/(
    user-service-env
    | \.git
    | \.mypy_cache
    | \.pytest_cache
    | \.tox
    | \.nox
    | dist
    | build
    | __pycache__
)/
'''

[tool.isort]
profile = "black"
line_length = 80
